### ISSUE TITLE
Adding characters to text files

### ISSUE THREAD

**Issue by Fantafaust** [DS-Pokemon-Rom-Editor/DSPRE#27]
App release Version: 1.12.4-beta
Game: SoulSilver, English

Issue:
opening text files will seemingly add junk characters to the input holders aka v2000/0001/0000 and the like, and keep doing it every time the files are opened.

Possible cause: 
I did unpack the rom with an earlier version, [1.11.1], perhaps the unpacked text files are different in some way between versions.

**Comment by Mixone-FinallyHere** [comment]
Originally posted by @Mixone-FinallyHere on 2024-11-01T13:05:03Z:

Resolved in 1.12.5
